version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: user_crud_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user-crud-net

  adminer:
    image: adminer
    container_name: adminer_user_crud
    restart: always
    ports:
      - 8080:8080
    networks:
      - user-crud-net

volumes:
  db_data:

networks:
  user-crud-net:
    driver: bridge
